### PR TITLE
Command Based IK Rework

### PR DESCRIPTION
**Pull request by green726**
Rewriting the IK to be better & be more command based

### CODE REVIEW

**Comment by green726** [comment]
Robot state machine has a "currentTrunkCommand" value. This holds the sole currently running trunk command (only one is allowed to run at a time). The trunk system contains the PIDs/FFs and wrappers to calculate motor voltages/percentages to get to desired using these PIDs. 

Trunk commands use trunk io to set motor voltages. Commands include go to pose, hold pose, hold translation with variable angle, move translation with coast angle, and coast translation/angle.

The commands can chain each other together. Something like AutoIntake should chain 2-3 of these trunk commands. When the trunk commands are running they set the "trunkReady" to false, and when they finish uninterrupted they set it to true.

This framework makes it very easy to handle edge cases as you just need to create a new command for it and don't need to touch pre-existing ones.

Compared to the old ik, the commands replace both the desired trunk position & the trunk mode, as well as all the sketchy trunk system periodic logic with a trillion booleans to enable/disable things. Much cleaner and no potential for conflicts (in terms of trunk movements).

**Comment by green726** [comment]
@dezash123 DESMOD why you push targeting system to the command-based IK branch???

**Comment by dezash123** [comment]
Im slightly reworking it so i want to make it work with ur code and this is easier than creating a separate branch

**Comment by green726** [comment]
Ok sounds good

**Pull request merged**
